### ISSUE TITLE
This tool not check ARB on recovery rom and fastboot rom

### ISSUE THREAD

**Issue by ale8530** [XiaomiFirmwareUpdater/miui_arb_checker#1]
I have try this tool,but not working

`ale8530@vmi81507:~/miui.it/new_roms/miui_arb_checker-master$ python3 miui_arb_checker.py nitrogen_images_9.5.9_20190509.0000.00_9.0_cn_1575b40646.tgz
Checking ARB from Fastboot ROM
ale8530@vmi81507:~/miui.it/new_roms/miui_arb_checker-master$ python3 miui_arb_checker.py miui_MIMAX3_9.5.9_c2cf21a1f8_9.0.zip
Checking ARB from Recovery ROM
xbl file extracted successfully.`

**Comment by yshalsager** [comment]
Thanks for reporting. @ale8530 
I've fixed a couple of derps, now it works as it should do.
```
$python3 miui_arb_checker.py miui_MIMAX3_9.5.9_c2cf21a1f8_9.0.zip
Checking ARB from Recovery ROM
xbl file extracted successfully.
ARB index is: 4
Note: sometimes this can be inaccurate!
Be sure to check curring anti number using fastboot or from XDA/MIUI forum.
```
```
$python3 miui_arb_checker.py nitrogen_images_9.5.9_20190509.0000.00_9.0_cn_1575b40646.tgz 
Checking ARB from Fastboot ROM
flashing script extracted successfully.
ARB index is: 4
```

**Comment by ale8530** [comment]
Ok fixed and open new issue for specific device-->https://github.com/XiaomiFirmwareUpdater/miui_arb_checker/issues/3
