### ISSUE TITLE
Can you improve control with recovery zip roms?

### ISSUE THREAD

**Issue by ale8530** [XiaomiFirmwareUpdater/miui_arb_checker#4]
`python3 miui_arb_checker.py miui_HMNote5_9.5.16_14b3f8abb0_9.0.zip
Checking ARB from Recovery ROM
xbl file extracted successfully.
ARB index is: 3
Note: sometimes this can be inaccurate!
Be sure to check curring anti number using fastboot or from XDA/MIUI forum.`

Fastboot has:
CURRENT_ANTI_VER=4

I noticed that you entered this notice "**Note: sometimes this can be inaccurate!**"

Do you think it is possible to optimize the recovery rom checker?

Thanks for attention

**Comment by yshalsager** [comment]
Hello @ale8530
As discussed in issue #2, there's no perfect way currently to get the ARB index from recovery roms. Unfortunately I don't have any idea about how it can be improved.

**Comment by ale8530** [comment]
Thanks
